USE ROLE ACCOUNTADMIN;
 
CREATE OR REPLACE DATABASE MY_PIPELINE_DB;
 
CREATE OR REPLACE SCHEMA MY_PIPELINE_DB.RAW;
 
CREATE OR REPLACE SCHEMA MY_PIPELINE_DB.ANALYTICS;
 
USE DATABASE MY_PIPELINE_DB;


CREATE OR REPLACE STORAGE INTEGRATION s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::783728775072:role/snowflake-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://vishal-elt-pipeline/raw_data/');


DESC INTEGRATION s3_integration;


CREATE OR REPLACE FILE FORMAT my_json_format
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;
 
USE SCHEMA RAW;
CREATE OR REPLACE STAGE s3_raw_stage
  STORAGE_INTEGRATION = s3_integration
  URL = 's3://vishal-elt-pipeline/raw_data/'
  FILE_FORMAT = my_json_format;
 
LIST @s3_raw_stage;

USE SCHEMA RAW;
 
CREATE OR REPLACE TABLE RAW_USERS (
  RAW_DATA VARIANT
);
 
CREATE OR REPLACE TABLE RAW_COMPANIES (
  RAW_DATA VARIANT
);


COPY INTO RAW_USERS
FROM @s3_raw_stage/users.json;
 

COPY INTO RAW_COMPANIES
FROM @s3_raw_stage/companies.json;


USE SCHEMA ANALYTICS;
 
CREATE OR REPLACE VIEW VW_USERS AS
SELECT
    RAW_DATA:id::NUMBER AS user_id,
    RAW_DATA:name::STRING AS full_name,
    RAW_DATA:username::STRING AS username,
    RAW_DATA:email::STRING AS email,
    RAW_DATA:address.city::STRING AS city
FROM
    MY_PIPELINE_DB.RAW.RAW_USERS;
CREATE OR REPLACE VIEW VW_COMPANIES AS
SELECT
    RAW_DATA:Symbol::STRING AS symbol,
    RAW_DATA:Name::STRING AS name,
    RAW_DATA:Sector::STRING AS sector
FROM
    MY_PIPELINE_DB.RAW.RAW_COMPANIES;


SELECT * FROM VW_USERS LIMIT 10;
SELECT * FROM VW_COMPANIES LIMIT 10;